export const REGISTER_STEP2_REQUEST = "RegisterReducer/REGISTER_STEP2_REQUEST";
export const REGISTER_STEP2_SUCCESS = "RegisterReducer/REGISTER_STEP2_SUCCESS";
export const REGISTER_STEP2_FAILED = "RegisterReducer/REGISTER_STEP2_FAILED";
